if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="diags-4";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

unitsize(1cm);
pair A,B,C,D;
A=W;
B=(1,2)+W;
C=(5,2)+E;
D=(4,0)+E;
label("$T_pM$",C,SE);
draw(A--B--C--D--cycle);
pair M=(2.5,1);
label("$p$",M,S);
pair X=M+(-2.5,2.5);
pair Y=M+(2.5,2.5);
fill(X..M..Y--cycle,white);
draw(X..M..Y);
draw(ellipse(M+(0,2.5),2.5,.5));
dot(M);
label("$v$",M+2E,S);
draw(M--M+2E,linewidth(.2mm),EndArrow);
draw(arc(M+(0,2.5),2.5,270,315),linewidth(.2mm),EndArcArrow);
