if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="diags-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

pair A,B,C,D,E,F,G,H;
unitsize(1cm);
A=(0,1);
B=(1,1);
C=(2,1);
D=(3,1);
E=(0,0);
F=(1,0);
G=(2,0);
H=(3,0);
dot(A);
dot(B);
dot(C);
dot(D);
dot(E);
dot(F);
dot(G);
dot(H);
draw(A--F);
draw(A--G);
draw(A--H);
draw(B--E);
draw(B--G);
draw(B--H);
draw(C--E);
draw(C--F);
draw(C--H);
draw(D--E);
draw(D--F);
draw(D--G);
label("1",A,N);
label("2",B,N);
label("3",C,N);
label("4",D,N);
label("5",E,S);
label("6",F,S);
label("7",G,S);
label("8",H,S);
